### ISSUE TITLE
Send caller to voicemail when no-one answers

### ISSUE THREAD

**Issue by vitorio** [SamyPesse/betty#13]
Right now, when no-one answers, betty says, "Your call could not be processed for the moment. Sorry for the inconvenient."

It would be nice if the call could be sent to voicemail.

**Comment by SamyPesse** [comment]
That's a bug, it should not happen: https://github.com/SamyPesse/betty/blob/master/lib/routes/call.js#L93

**Comment by SamyPesse** [comment]
Can you give me some request logs from twilio  when that happens ?

**Comment by vitorio** [comment]
Is there a good way to export logs from twilio.com?  I've shut down my betty instance at the moment.

Looking at the logs on the twilio.com, it looks like betty is providing a `localhost` URL in the TwiML of `/twiml/call` instead of rewriting it to include the betty instance's URL and port:

```xml
<?xml version="1.0" encoding="UTF-8"?><Response><Say voice="alice" language="en-us">Thanks for calling XXXX, your call will be transfered to one of our team members</Say><Dial callerId="+1 512-xxx-yyyy" action="http://localhost:3000/twiml/call/status" timeout="10"><Number>+1 631-xxx-yyyy</Number><Client>vititorio</Client></Dial></Response>
```

**Comment by SamyPesse** [comment]
You need to set `HOST` (By default it's `http://localhost:{port}`

**Comment by vitorio** [comment]
Ah.  Is that the default?  When betty starts, it reports it's binding to 0.0.0.0 (all interfaces), so I was able to access it from an external IP, as was Twilio.

If `HOST` is required, it should be included in config.js' as required to point to an external IP.  Seems like it should know what IP it's being accessed through, though.
