### ISSUE TITLE
Dashboard login

### ISSUE THREAD

**Issue by intelliot** [SamyPesse/betty#18]
What's the User Name?

![screen_shot_2015-05-09_at_3_55_40_pm](https://cloud.githubusercontent.com/assets/81505/7552346/fc83fb66-f663-11e4-9ab0-c08ba4bbf969.png)

**Comment by SamyPesse** [comment]
The username is one of the team members's name and the passort is the
secret set in the configuration.

On Sunday, May 10, 2015, Elliot Lee notifications@github.com wrote:

> What's the User Name?
> 
> [image: screen_shot_2015-05-09_at_3_55_40_pm]
> https://cloud.githubusercontent.com/assets/81505/7552346/fc83fb66-f663-11e4-9ab0-c08ba4bbf969.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SamyPesse/betty/issues/18.

## 

Sent from Gmail Mobile

**Comment by intelliot** [comment]
:+1:
