### ISSUE TITLE
Installed and ran "betty" but getting Basic Auth window

### ISSUE THREAD

**Issue by noahmatisoff** [SamyPesse/betty#24]
What's wrong with the setup?  I followed through the README and set the config ENV vars listed there.

**Comment by SamyPesse** [comment]
You need to enter the name of a team member and the secret.

**Comment by noahmatisoff** [comment]
Tried that to no avail.

**Comment by noahmatisoff** [comment]
It intermittently works and I get this when it does work: {"error":"The requested resource /2010-04-01/Accounts/SKc7376b5fcfa3ab7db48a3fee9fb032c6/Usage/Records.json was not found","code":404}
