### ISSUE TITLE
Handle machine when forwarding calls

### ISSUE THREAD

**Issue by SamyPesse** [SamyPesse/betty#6]
If a team member has its phone in plane mode, it will forward the call to him.

Machine handling is not available in TwiML (only in the api: https://www.twilio.com/docs/api/rest/making-calls#handling-outcomes-answering-machines), but it's probably possible to start the call forward using the rest api instead of `<Dial>`

**Comment by vitorio** [comment]
When you handle this, you also want the caller to opt-into accepting the call.  Betty should ask, "press <number> to accept this call," and the team member should have to press the number, or eventually betty will time out and try someone else.  This is to avoid situations where someone accidentally answers, or when Twilio does not accurately detect that it has reached a voicemail box.
