### ISSUE TITLE
unable to start betty

### ISSUE THREAD

**Issue by gingerlime** [SamyPesse/betty#7]
Looks really great! Thanks for creating Betty !

I'm having some beginner's problems getting betty running however. I've created a new Ubuntu 14.04 vps and installed node and npm, exported `TEAM`, but when I start `betty` nothing really happens. No error, nothing. I'm guessing some environment variables are missing (`SECRET` etc?) but would be nice(r) to get some kind of indication of what's going on to help getting things up and running... The getting started section seems a bit thin on which settings are mandatory and which ones are optional as well.

**Comment by gingerlime** [comment]
... actually even after exporting all configuration settings it just won't start and no indication of what may have gone wrong.

**Comment by SamyPesse** [comment]
You should get a log that tells you: `Listening at http://0.0.0.0:5000`.

You can change the running port by exporting `PORT` (see the list of configurations at https://github.com/SamyPesse/betty#configuration)

**Comment by gingerlime** [comment]
It doesn't say anything or produces any logs. It just silently stops. I exported all configuration options, but still - just nothing happens:

```
root@test:~# betty
root@test:~# 
```

**Comment by gingerlime** [comment]
ok, looks like I just installed nodejs incorrectly... sorry, my mistake.

**Comment by SamyPesse** [comment]
Ok :)
